version: '2'
services:

  consul:
    image: "consul:1.1.0"
    hostname: "consul"
    command: "agent -dev -client 0.0.0.0"
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  vault:
    depends_on:
    - consul
#    image: "vault:0.11.5"
#    Unfortuntely vault docker have no glibc and don't support plugins. https://github.com/immutability-io/vault-ethereum/issues/2
    build: .
    hostname: "vault"
    links:
    - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
    - "8200:8200"
    volumes:
      - ./bin/:/vault_plugin
      - ./scripts/config/vault:/config
      - ./Makefile:/Makefile
      - ./scripts/tools:/tools
    entrypoint: /tools/wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/vault-config-with-consul.hcl -log-level=debug
